[package]
name = "readpcap"
version = "0.1.0"
authors = ["Joonas Koivunen <joonas.koivunen@gmail.com>"]

[dependencies]
byteorder = "1"
eventstore-tcp = { git = "https://github.com/koivunej/eventstore-tcp.git" }
tokio-io = "*"
bytes = "*"
